server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

testConfig:
  welcome-msg: Hello

spring:
  cloud:
    #RabbitMQ
    rabbitmq:
       addresses: localhost:5672
       username: test
       password: test
       virtual_host: /

database:
  postgre:
    url: jdbc:postgresql://localhost:5432/users
    username: userservice
    password: userservicepass
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  mysql:
    url: jdbc:mysql://localhost:3306/oauth2?autoReconnect=true&useSSL=false&&serverTimezone=UTC
    username: oauth2
    password: Oauth2
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  # h2:
  #   console:
  #     enabled: true


# server:
#   port: 8002
