# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

testConfig:
  welcome-msg: Hello


database:
  postgre:
    url: jdbc:postgresql://localhost:5433/oauth2
    username: oauth2
    password: oauth2
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  mysql:
    url: jdbc:mysql://localhost:3306/oauth2?autoReconnect=true&useSSL=false&&serverTimezone=UTC
    username: oauth2
    password: Oauth2
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql


spring:
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  # h2:
  #   console:
  #     enabled: true

logging:
  level: debug

# server:
#   port: 8002