# Items that apply to ALL profiles:
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckInterval: 10s
    #RabbitMQ
    rabbitmq:
       addresses: localhost:5672
       username: test
       password: test
       virtual_host: /
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
      isolation:
          thread:
              timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000