# Items that apply to ALL profiles:
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/
spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckInterval: 10s
        prefer-ip-address: true
    #RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: test
    password: test
      # virtual_host: /
