# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

spring:
  cloud:
    config:
      failFast: true


security: 
  user: 
    name: user
    password: password

