zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    account-service:
      path: /accounts/**
      stripPrefix: false
    robot-service: 
      path: /robots/**
      stripPrefix: false
  SendErrorFilter:
    post:
      disable: true

spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckInterval: 15s
