zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    account-service:
      path: /accounts/**
    robot-service: 
      path:/robots/**
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckInterval: 15s
