server:
  port: 5000

# Hibernate
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

###
# Data Source Configuration
###
database:
  postgre:
    url: jdbc:postgresql://localhost:5432/oauth
    username: oauth
    password: oauth
    driver-class-name: org.postgresql.Driver
    initialize: true

###
# JWT Keystore password
###
keystore:
  password: jvkEa89en6jN7KkQ

